### ISSUE TITLE
Add RgGen

### ISSUE THREAD

**Issue by taichi-ishitani** [mattvenn/awesome-opensource-asic#6]
Hi Matt,

I'm developing a code generator tool for CSR named `RgGen`.
https://github.com/rggen/rggen
Can I add my tool to your list?
If yes, which category should I use?

Regards,
Taichi Ishitani

**Comment by mattvenn** [comment]
Hi, yes please make a PR to include it in the 'generators' section.

**Comment by taichi-ishitani** [comment]
Thank you for your reply.
I just opened a PR for this #11.
